; ***************************************************************************
; GENERATED:
;   Time:    17-Jun-2015 15:08PM
;   By:      Brian Lee
;   Command: rgen g pe_low_level -t pe.rb
; ***************************************************************************
; ENVIRONMENT:
;   Application
;     Vault:     sync://sync-15088:15088/Projects/common_tester_blocks/rgen_blocks/tester/Debuggers/tool_data/rgen
;     Version:   1.1.0
;     Workspace: C:/Users/b07408/Documents/RGen/debuggers
;   RGen
;     Vault:     sync://sync-15088:15088/Projects/common_tester_blocks/rgen
;     Version:   2.5.0.pre60
;     Workspace: C:/Users/b07408/.rgen/gems/ruby/1.9.1/gems/rgen_core-2.5.0.pre60
; ***************************************************************************
; ######################################################################
; ## Verify different shift_ir lengths
; ######################################################################
jtag_start
jtag_ir 4t 7
jtag_ir 5t 8
jtag_ir 6t 9
jtag_end
